#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaiTapLon_Web
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QLPhim")]
	public partial class DBMoviesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertPhim(Phimm instance);
    partial void UpdatePhim(Phimm instance);
    partial void DeletePhim(Phimm instance);
    #endregion
		
		public DBMoviesDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["QLPhimConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DBMoviesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBMoviesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBMoviesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBMoviesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Phimm> Phimx
		{
			get
			{
				return this.GetTable<Phimm>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Phim")]
	public partial class Phimm : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaPhim;
		
		private string _TenPhim;
		
		private string _MaNuocSX;
		
		private string _MaHang;
		
		private string _MaTheLoai;
		
		private string _DaoDien;
		
		private string _NuDienVienChinh;
		
		private string _NamDienVienChinh;
		
		private string _NoiDungChinh;
		
		private System.Nullable<System.DateTime> _NgayKhoiChieu;
		
		private System.Nullable<System.DateTime> _NgayKetThuc;
		
		private System.Nullable<double> _TongChiPhi;
		
		private string _Anh;
		
		private System.Nullable<int> _ThoiLuong;
		
		private System.Nullable<int> _NamSX;
		
		private string _Trailer;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaPhimChanging(string value);
    partial void OnMaPhimChanged();
    partial void OnTenPhimChanging(string value);
    partial void OnTenPhimChanged();
    partial void OnMaNuocSXChanging(string value);
    partial void OnMaNuocSXChanged();
    partial void OnMaHangChanging(string value);
    partial void OnMaHangChanged();
    partial void OnMaTheLoaiChanging(string value);
    partial void OnMaTheLoaiChanged();
    partial void OnDaoDienChanging(string value);
    partial void OnDaoDienChanged();
    partial void OnNuDienVienChinhChanging(string value);
    partial void OnNuDienVienChinhChanged();
    partial void OnNamDienVienChinhChanging(string value);
    partial void OnNamDienVienChinhChanged();
    partial void OnNoiDungChinhChanging(string value);
    partial void OnNoiDungChinhChanged();
    partial void OnNgayKhoiChieuChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayKhoiChieuChanged();
    partial void OnNgayKetThucChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayKetThucChanged();
    partial void OnTongChiPhiChanging(System.Nullable<double> value);
    partial void OnTongChiPhiChanged();
    partial void OnAnhChanging(string value);
    partial void OnAnhChanged();
    partial void OnThoiLuongChanging(System.Nullable<int> value);
    partial void OnThoiLuongChanged();
    partial void OnNamSXChanging(System.Nullable<int> value);
    partial void OnNamSXChanged();
    partial void OnTrailerChanging(string value);
    partial void OnTrailerChanged();
    #endregion
		
		public Phimm()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaPhim", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaPhim
		{
			get
			{
				return this._MaPhim;
			}
			set
			{
				if ((this._MaPhim != value))
				{
					this.OnMaPhimChanging(value);
					this.SendPropertyChanging();
					this._MaPhim = value;
					this.SendPropertyChanged("MaPhim");
					this.OnMaPhimChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenPhim", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string TenPhim
		{
			get
			{
				return this._TenPhim;
			}
			set
			{
				if ((this._TenPhim != value))
				{
					this.OnTenPhimChanging(value);
					this.SendPropertyChanging();
					this._TenPhim = value;
					this.SendPropertyChanged("TenPhim");
					this.OnTenPhimChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNuocSX", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string MaNuocSX
		{
			get
			{
				return this._MaNuocSX;
			}
			set
			{
				if ((this._MaNuocSX != value))
				{
					this.OnMaNuocSXChanging(value);
					this.SendPropertyChanging();
					this._MaNuocSX = value;
					this.SendPropertyChanged("MaNuocSX");
					this.OnMaNuocSXChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHang", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string MaHang
		{
			get
			{
				return this._MaHang;
			}
			set
			{
				if ((this._MaHang != value))
				{
					this.OnMaHangChanging(value);
					this.SendPropertyChanging();
					this._MaHang = value;
					this.SendPropertyChanged("MaHang");
					this.OnMaHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTheLoai", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string MaTheLoai
		{
			get
			{
				return this._MaTheLoai;
			}
			set
			{
				if ((this._MaTheLoai != value))
				{
					this.OnMaTheLoaiChanging(value);
					this.SendPropertyChanging();
					this._MaTheLoai = value;
					this.SendPropertyChanged("MaTheLoai");
					this.OnMaTheLoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DaoDien", DbType="NVarChar(50)")]
		public string DaoDien
		{
			get
			{
				return this._DaoDien;
			}
			set
			{
				if ((this._DaoDien != value))
				{
					this.OnDaoDienChanging(value);
					this.SendPropertyChanging();
					this._DaoDien = value;
					this.SendPropertyChanged("DaoDien");
					this.OnDaoDienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NuDienVienChinh", DbType="NVarChar(50)")]
		public string NuDienVienChinh
		{
			get
			{
				return this._NuDienVienChinh;
			}
			set
			{
				if ((this._NuDienVienChinh != value))
				{
					this.OnNuDienVienChinhChanging(value);
					this.SendPropertyChanging();
					this._NuDienVienChinh = value;
					this.SendPropertyChanged("NuDienVienChinh");
					this.OnNuDienVienChinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NamDienVienChinh", DbType="NVarChar(50)")]
		public string NamDienVienChinh
		{
			get
			{
				return this._NamDienVienChinh;
			}
			set
			{
				if ((this._NamDienVienChinh != value))
				{
					this.OnNamDienVienChinhChanging(value);
					this.SendPropertyChanging();
					this._NamDienVienChinh = value;
					this.SendPropertyChanged("NamDienVienChinh");
					this.OnNamDienVienChinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoiDungChinh", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string NoiDungChinh
		{
			get
			{
				return this._NoiDungChinh;
			}
			set
			{
				if ((this._NoiDungChinh != value))
				{
					this.OnNoiDungChinhChanging(value);
					this.SendPropertyChanging();
					this._NoiDungChinh = value;
					this.SendPropertyChanged("NoiDungChinh");
					this.OnNoiDungChinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayKhoiChieu", DbType="Date")]
		public System.Nullable<System.DateTime> NgayKhoiChieu
		{
			get
			{
				return this._NgayKhoiChieu;
			}
			set
			{
				if ((this._NgayKhoiChieu != value))
				{
					this.OnNgayKhoiChieuChanging(value);
					this.SendPropertyChanging();
					this._NgayKhoiChieu = value;
					this.SendPropertyChanged("NgayKhoiChieu");
					this.OnNgayKhoiChieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayKetThuc", DbType="Date")]
		public System.Nullable<System.DateTime> NgayKetThuc
		{
			get
			{
				return this._NgayKetThuc;
			}
			set
			{
				if ((this._NgayKetThuc != value))
				{
					this.OnNgayKetThucChanging(value);
					this.SendPropertyChanging();
					this._NgayKetThuc = value;
					this.SendPropertyChanged("NgayKetThuc");
					this.OnNgayKetThucChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TongChiPhi", DbType="Float")]
		public System.Nullable<double> TongChiPhi
		{
			get
			{
				return this._TongChiPhi;
			}
			set
			{
				if ((this._TongChiPhi != value))
				{
					this.OnTongChiPhiChanging(value);
					this.SendPropertyChanging();
					this._TongChiPhi = value;
					this.SendPropertyChanged("TongChiPhi");
					this.OnTongChiPhiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Anh", DbType="NVarChar(250)")]
		public string Anh
		{
			get
			{
				return this._Anh;
			}
			set
			{
				if ((this._Anh != value))
				{
					this.OnAnhChanging(value);
					this.SendPropertyChanging();
					this._Anh = value;
					this.SendPropertyChanged("Anh");
					this.OnAnhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThoiLuong", DbType="Int")]
		public System.Nullable<int> ThoiLuong
		{
			get
			{
				return this._ThoiLuong;
			}
			set
			{
				if ((this._ThoiLuong != value))
				{
					this.OnThoiLuongChanging(value);
					this.SendPropertyChanging();
					this._ThoiLuong = value;
					this.SendPropertyChanged("ThoiLuong");
					this.OnThoiLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NamSX", DbType="Int")]
		public System.Nullable<int> NamSX
		{
			get
			{
				return this._NamSX;
			}
			set
			{
				if ((this._NamSX != value))
				{
					this.OnNamSXChanging(value);
					this.SendPropertyChanging();
					this._NamSX = value;
					this.SendPropertyChanged("NamSX");
					this.OnNamSXChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Trailer", DbType="NVarChar(MAX)")]
		public string Trailer
		{
			get
			{
				return this._Trailer;
			}
			set
			{
				if ((this._Trailer != value))
				{
					this.OnTrailerChanging(value);
					this.SendPropertyChanging();
					this._Trailer = value;
					this.SendPropertyChanged("Trailer");
					this.OnTrailerChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
