<?xml version="1.0" encoding="utf-8"?><Database Name="QLPhim" Class="DBMoviesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=LAPTOP-FBMKAQ20\KTEAM;Initial Catalog=QLPhim;Integrated Security=True;MultipleActiveResultSets=True;Application Name=EntityFramework" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="QLPhimConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Phim" Member="Phims">
    <Type Name="Phim">
      <Column Name="MaPhim" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenPhim" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="MaNuocSX" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="MaHang" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="MaTheLoai" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="DaoDien" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NuDienVienChinh" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NamDienVienChinh" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NoiDungChinh" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="NgayKhoiChieu" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="NgayKetThuc" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="TongChiPhi" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Anh" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="ThoiLuong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NamSX" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Trailer" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
</Database>