#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaiTapLon_Web
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QLPhim")]
	public partial class DBScreeningsDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertBuoiChieu(BuoiChieu instance);
    partial void UpdateBuoiChieu(BuoiChieu instance);
    partial void DeleteBuoiChieu(BuoiChieu instance);
    #endregion
		
		public DBScreeningsDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["QLPhimConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DBScreeningsDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBScreeningsDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBScreeningsDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBScreeningsDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<BuoiChieu> BuoiChieus
		{
			get
			{
				return this.GetTable<BuoiChieu>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BuoiChieu")]
	public partial class BuoiChieu : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaBuoiChieu;
		
		private string _MaPhim;
		
		private string _MaRap;
		
		private string _MaPhong;
		
		private System.Nullable<System.DateTime> _NgayChieu;
		
		private System.Nullable<int> _GioChieu;
		
		private System.Nullable<decimal> _GiaVe;
		
		private System.Nullable<int> _SoVeDaBan;
		
		private System.Nullable<double> _TongTien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaBuoiChieuChanging(string value);
    partial void OnMaBuoiChieuChanged();
    partial void OnMaPhimChanging(string value);
    partial void OnMaPhimChanged();
    partial void OnMaRapChanging(string value);
    partial void OnMaRapChanged();
    partial void OnMaPhongChanging(string value);
    partial void OnMaPhongChanged();
    partial void OnNgayChieuChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayChieuChanged();
    partial void OnGioChieuChanging(System.Nullable<int> value);
    partial void OnGioChieuChanged();
    partial void OnGiaVeChanging(System.Nullable<decimal> value);
    partial void OnGiaVeChanged();
    partial void OnSoVeDaBanChanging(System.Nullable<int> value);
    partial void OnSoVeDaBanChanged();
    partial void OnTongTienChanging(System.Nullable<double> value);
    partial void OnTongTienChanged();
    #endregion
		
		public BuoiChieu()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaBuoiChieu", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaBuoiChieu
		{
			get
			{
				return this._MaBuoiChieu;
			}
			set
			{
				if ((this._MaBuoiChieu != value))
				{
					this.OnMaBuoiChieuChanging(value);
					this.SendPropertyChanging();
					this._MaBuoiChieu = value;
					this.SendPropertyChanged("MaBuoiChieu");
					this.OnMaBuoiChieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaPhim", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string MaPhim
		{
			get
			{
				return this._MaPhim;
			}
			set
			{
				if ((this._MaPhim != value))
				{
					this.OnMaPhimChanging(value);
					this.SendPropertyChanging();
					this._MaPhim = value;
					this.SendPropertyChanged("MaPhim");
					this.OnMaPhimChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaRap", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string MaRap
		{
			get
			{
				return this._MaRap;
			}
			set
			{
				if ((this._MaRap != value))
				{
					this.OnMaRapChanging(value);
					this.SendPropertyChanging();
					this._MaRap = value;
					this.SendPropertyChanged("MaRap");
					this.OnMaRapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaPhong", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string MaPhong
		{
			get
			{
				return this._MaPhong;
			}
			set
			{
				if ((this._MaPhong != value))
				{
					this.OnMaPhongChanging(value);
					this.SendPropertyChanging();
					this._MaPhong = value;
					this.SendPropertyChanged("MaPhong");
					this.OnMaPhongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayChieu", DbType="Date")]
		public System.Nullable<System.DateTime> NgayChieu
		{
			get
			{
				return this._NgayChieu;
			}
			set
			{
				if ((this._NgayChieu != value))
				{
					this.OnNgayChieuChanging(value);
					this.SendPropertyChanging();
					this._NgayChieu = value;
					this.SendPropertyChanged("NgayChieu");
					this.OnNgayChieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GioChieu", DbType="Int")]
		public System.Nullable<int> GioChieu
		{
			get
			{
				return this._GioChieu;
			}
			set
			{
				if ((this._GioChieu != value))
				{
					this.OnGioChieuChanging(value);
					this.SendPropertyChanging();
					this._GioChieu = value;
					this.SendPropertyChanged("GioChieu");
					this.OnGioChieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GiaVe", DbType="Money")]
		public System.Nullable<decimal> GiaVe
		{
			get
			{
				return this._GiaVe;
			}
			set
			{
				if ((this._GiaVe != value))
				{
					this.OnGiaVeChanging(value);
					this.SendPropertyChanging();
					this._GiaVe = value;
					this.SendPropertyChanged("GiaVe");
					this.OnGiaVeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoVeDaBan", DbType="Int")]
		public System.Nullable<int> SoVeDaBan
		{
			get
			{
				return this._SoVeDaBan;
			}
			set
			{
				if ((this._SoVeDaBan != value))
				{
					this.OnSoVeDaBanChanging(value);
					this.SendPropertyChanging();
					this._SoVeDaBan = value;
					this.SendPropertyChanged("SoVeDaBan");
					this.OnSoVeDaBanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TongTien", DbType="Float")]
		public System.Nullable<double> TongTien
		{
			get
			{
				return this._TongTien;
			}
			set
			{
				if ((this._TongTien != value))
				{
					this.OnTongTienChanging(value);
					this.SendPropertyChanging();
					this._TongTien = value;
					this.SendPropertyChanged("TongTien");
					this.OnTongTienChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
