<?xml version="1.0" encoding="utf-8"?><Database Name="QLPhim" Class="DBTicketsDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=LAPTOP-FBMKAQ20\KTEAM;Initial Catalog=QLPhim;Integrated Security=True;MultipleActiveResultSets=True;Application Name=EntityFramework" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="QLPhimConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Ve" Member="Ves">
    <Type Name="Ve">
      <Column Name="MaVe" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaBuoiChieu" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="HangGhe" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="SoGhe" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LoaiGhe" Type="System.String" DbType="NVarChar(25)" CanBeNull="true" />
      <Column Name="TienVe" Type="System.Decimal" DbType="Money" CanBeNull="true" />
    </Type>
  </Table>
</Database>