#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaiTapLon_Web
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QLPhim")]
	public partial class DBTicketsDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertVe(Ve instance);
    partial void UpdateVe(Ve instance);
    partial void DeleteVe(Ve instance);
    #endregion
		
		public DBTicketsDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["QLPhimConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DBTicketsDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBTicketsDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBTicketsDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBTicketsDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Ve> Ves
		{
			get
			{
				return this.GetTable<Ve>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Ve")]
	public partial class Ve : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaVe;
		
		private string _MaBuoiChieu;
		
		private string _HangGhe;
		
		private int _SoGhe;
		
		private string _LoaiGhe;
		
		private System.Nullable<decimal> _TienVe;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaVeChanging(string value);
    partial void OnMaVeChanged();
    partial void OnMaBuoiChieuChanging(string value);
    partial void OnMaBuoiChieuChanged();
    partial void OnHangGheChanging(string value);
    partial void OnHangGheChanged();
    partial void OnSoGheChanging(int value);
    partial void OnSoGheChanged();
    partial void OnLoaiGheChanging(string value);
    partial void OnLoaiGheChanged();
    partial void OnTienVeChanging(System.Nullable<decimal> value);
    partial void OnTienVeChanged();
    #endregion
		
		public Ve()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaVe", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaVe
		{
			get
			{
				return this._MaVe;
			}
			set
			{
				if ((this._MaVe != value))
				{
					this.OnMaVeChanging(value);
					this.SendPropertyChanging();
					this._MaVe = value;
					this.SendPropertyChanged("MaVe");
					this.OnMaVeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaBuoiChieu", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string MaBuoiChieu
		{
			get
			{
				return this._MaBuoiChieu;
			}
			set
			{
				if ((this._MaBuoiChieu != value))
				{
					this.OnMaBuoiChieuChanging(value);
					this.SendPropertyChanging();
					this._MaBuoiChieu = value;
					this.SendPropertyChanged("MaBuoiChieu");
					this.OnMaBuoiChieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HangGhe", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string HangGhe
		{
			get
			{
				return this._HangGhe;
			}
			set
			{
				if ((this._HangGhe != value))
				{
					this.OnHangGheChanging(value);
					this.SendPropertyChanging();
					this._HangGhe = value;
					this.SendPropertyChanged("HangGhe");
					this.OnHangGheChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoGhe", DbType="Int NOT NULL")]
		public int SoGhe
		{
			get
			{
				return this._SoGhe;
			}
			set
			{
				if ((this._SoGhe != value))
				{
					this.OnSoGheChanging(value);
					this.SendPropertyChanging();
					this._SoGhe = value;
					this.SendPropertyChanged("SoGhe");
					this.OnSoGheChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoaiGhe", DbType="NVarChar(25)")]
		public string LoaiGhe
		{
			get
			{
				return this._LoaiGhe;
			}
			set
			{
				if ((this._LoaiGhe != value))
				{
					this.OnLoaiGheChanging(value);
					this.SendPropertyChanging();
					this._LoaiGhe = value;
					this.SendPropertyChanged("LoaiGhe");
					this.OnLoaiGheChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TienVe", DbType="Money")]
		public System.Nullable<decimal> TienVe
		{
			get
			{
				return this._TienVe;
			}
			set
			{
				if ((this._TienVe != value))
				{
					this.OnTienVeChanging(value);
					this.SendPropertyChanging();
					this._TienVe = value;
					this.SendPropertyChanged("TienVe");
					this.OnTienVeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
